default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV["DATABASE_HOST"] || "localhost" %>
  port:     <%= ENV["DATABASE_PORT"] || 5432 %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  database: <%= ENV["DATABASE_NAME"] || "dabliu_development" %>

development:
  <<: *default
  database: dabliu_development

test:
  <<: *default
  database: dabliu_test

production:
  <<: *default
