default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: dabliu_development

test:
  <<: *default
  database: dabliu_test

production:
  <<: *default
  database: dabliu_production
